import type { L1AnswerOption, L1BodyReferenceLesson, L1Challenge } from './l1BodyReference.types';

const option = (id: string, label: string, landmarkId: string, textDescription: string): L1AnswerOption => ({ id, label, landmarkId, textDescription });
const pair = (first: L1AnswerOption, second: L1AnswerOption): readonly L1AnswerOption[] => [first, second];
const item = (entry: L1Challenge): L1Challenge => entry;

const leftFront = option('patient-left', 'Mão 1', 'patient-left-hand', 'Mão apresentada à direita de quem observa a vista frontal.');
const rightFront = option('observer-left', 'Mão 2', 'patient-right-hand', 'Mão apresentada à esquerda de quem observa a vista frontal.');
const leftBack = option('patient-left', 'Mão 1', 'patient-left-hand', 'Mão apresentada à esquerda de quem observa a vista posterior.');
const rightBack = option('patient-right', 'Mão 2', 'patient-right-hand', 'Mão apresentada à direita de quem observa a vista posterior.');

export const L1_BODY_REFERENCE: L1BodyReferenceLesson = {
  id: 'lesson:v3:arc:spatial-orientation:l1-body-reference',
  title: 'O corpo como referência',
  audienceLabel: 'Prática de orientação espacial para o trabalho diário em radiologia',
  version: '1.0.0-draft',
  sources: [
    { id: 'fipat-ta2-part-1', title: 'Terminologia Anatomica 2, Part 1', authority: 'FIPAT / IFAA', edition: 'TA2 Part 1', sections: ['termos 7–12', '18–19', '32–35'], url: 'https://libraries.dal.ca/Fipat/ta2.html', consultedOn: '2026-08-27', use: 'Termos anatômicos normalizados; o texto em português é editorial e original.' },
    { id: 'ifaa-fipat-status', title: 'FIPAT Anatomical Terminology', authority: 'IFAA', edition: 'consulta web 2026-08-27', sections: ['TA2'], url: 'https://ifaa.net/committees/anatomical-terminology-fipat/', consultedOn: '2026-08-27', use: 'Proveniência e status da referência terminológica usada pela L1.' },
    { id: 'apple-hig-accessibility', title: 'Human Interface Guidelines — Accessibility e VoiceOver', authority: 'Apple', edition: 'consulta web 2026-08-27', sections: ['alternativas a gestos', 'VoiceOver', 'Reduce Motion', 'informação além de cor'], url: 'https://developer.apple.com/design/human-interface-guidelines/accessibility/', consultedOn: '2026-08-27', use: 'Controles alternativos e comunicação acessível da atividade.' },
  ],
  relationships: [
    { id: 'superior-inferior', label: 'superior / inferior', operationalDefinition: 'Superior aproxima uma estrutura da cabeça; inferior aproxima dos pés na referência anatômica.', visualCue: 'marcadores de cabeça e pés, não setas chamadas de eixos' },
    { id: 'anterior-posterior', label: 'anterior / posterior', operationalDefinition: 'Anterior aponta para a frente do corpo; posterior, para as costas, mesmo se a pessoa estiver deitada.', visualCue: 'silhueta frontal e posterior com contorno e rótulo' },
    { id: 'medial-lateral', label: 'medial / lateral', operationalDefinition: 'Medial se aproxima da linha mediana; lateral se afasta dela.', visualCue: 'linha mediana contínua e padrões de distância' },
    { id: 'proximal-distal', label: 'proximal / distal', operationalDefinition: 'Em um membro, proximal se aproxima da ligação com o tronco; distal se afasta dela.', visualCue: 'pontos de ligação do braço e segmentos com traços progressivos' },
    { id: 'superficial-deep', label: 'superficial / profundo', operationalDefinition: 'Superficial está mais perto da superfície corporal; profundo fica sob uma camada mais externa.', visualCue: 'camadas sólida e tracejada, identificadas também por texto' },
  ],
  challenges: [
    item({ id: 'l1-diagnostic-laterality', objectiveId: 'O-L1-lateralidade-corpo-observador', prompt: 'Você está diante de uma pessoa na posição anatômica. Qual mão pertence ao lado esquerdo dela?', accessiblePrompt: 'Escolha entre duas mãos numeradas mostradas no modelo e descritas sem indicar qual é correta.', answerOptions: pair(leftFront, rightFront), correctAnswerId: 'patient-left', evidenceKind: 'initial_independent', awardsXp: false, misconception: 'E-LAT-OBS', feedback: { correct: 'Você tomou o corpo examinado como referência, não o seu lado da tela.', incorrect: 'O lado direito ou esquerdo pertence ao corpo descrito. Troque a perspectiva do observador pela referência anatômica.' }, remediationChallengeId: 'l1-remediate-laterality', nextChallengeId: 'l1-laterality-transfer', nextActionLabel: 'Continuar para lateralidade em nova vista', reviewTargetId: 'review:l1:lateralidade-em-nova-postura', posture: 'anatomical', perspective: 'front' }),
    item({ id: 'l1-remediate-laterality', objectiveId: 'O-L1-lateralidade-corpo-observador', prompt: 'Prática guiada: siga a linha mediana e identifique o lado esquerdo do corpo mostrado.', accessiblePrompt: 'Prática guiada com duas mãos numeradas e uma descrição espacial sem indicar a resposta.', answerOptions: pair(leftFront, rightFront), correctAnswerId: 'patient-left', evidenceKind: 'assisted_practice', awardsXp: false, misconception: 'E-LAT-OBS', feedback: { correct: 'A linha mediana organiza os dois lados do corpo, independentemente de quem observa.', incorrect: 'Volte à linha mediana: ela separa os lados do corpo, não os lados da tela.' }, remediationChallengeId: 'l1-remediate-laterality', nextChallengeId: 'l1-laterality-transfer', nextActionLabel: 'Tentar lateralidade em nova vista', additionalRecoveryChallengeId: 'l1-laterality-recovery-2', reviewTargetId: 'review:l1:lateralidade-em-nova-postura', posture: 'anatomical', perspective: 'front' }),
    item({ id: 'l1-laterality-transfer', objectiveId: 'O-L1-lateralidade-corpo-observador', prompt: 'Agora observe a pessoa por trás. Qual mão pertence ao lado esquerdo do corpo?', accessiblePrompt: 'Escolha entre duas mãos numeradas em vista posterior; a descrição informa posições, não a resposta.', answerOptions: pair(leftBack, rightBack), correctAnswerId: 'patient-left', evidenceKind: 'later_independent_retrieval', awardsXp: true, misconception: 'E-LAT-OBS', feedback: { correct: 'A mudança de vista desloca a tela, não troca os lados do corpo.', incorrect: 'A vista posterior muda o que você vê à esquerda da tela, mas não muda o lado esquerdo da pessoa.' }, remediationChallengeId: 'l1-remediate-laterality', nextChallengeId: 'l1-superior-inferior', nextActionLabel: 'Continuar para relações do corpo', reviewTargetId: 'review:l1:lateralidade-em-nova-postura', posture: 'anatomical', perspective: 'back' }),
    item({ id: 'l1-superior-inferior', objectiveId: 'O-L1-superior-inferior', prompt: 'Qual marcador está mais próximo da cabeça na referência anatômica?', accessiblePrompt: 'Escolha entre dois marcadores numerados mostrados na silhueta.', answerOptions: pair(option('superior', 'Marcador 1', 'head-marker', 'Marcador junto à extremidade da cabeça.'), option('inferior', 'Marcador 2', 'foot-marker', 'Marcador junto à extremidade dos pés.')), correctAnswerId: 'superior', evidenceKind: 'later_independent_retrieval', awardsXp: true, misconception: 'E-REL', feedback: { correct: 'Superior descreve proximidade da cabeça, não a parte mais alta da tela.', incorrect: 'Use a referência cabeça–pés do corpo, não a altura do quadro.' }, remediationChallengeId: 'l1-assisted-superior-inferior', nextChallengeId: 'l1-medial-lateral', nextActionLabel: 'Continuar', reviewTargetId: 'review:l1:superior-inferior', posture: 'anatomical', perspective: 'front' }),
    item({ id: 'l1-medial-lateral', objectiveId: 'O-L1-medial-lateral', prompt: 'Qual marcador está mais próximo da linha mediana?', accessiblePrompt: 'Escolha entre dois marcadores numerados, um junto da linha tracejada e outro no braço.', answerOptions: pair(option('medial', 'Marcador 1', 'midline-marker', 'Marcador junto à linha tracejada central.'), option('lateral', 'Marcador 2', 'outer-arm-marker', 'Marcador junto ao contorno externo do braço.')), correctAnswerId: 'medial', evidenceKind: 'later_independent_retrieval', awardsXp: true, misconception: 'E-REL', feedback: { correct: 'Medial é a relação com a linha mediana.', incorrect: 'Compare cada marcador com a linha mediana, não com a borda da tela.' }, remediationChallengeId: 'l1-assisted-medial-lateral', nextChallengeId: 'l1-proximal-distal', nextActionLabel: 'Continuar', reviewTargetId: 'review:l1:medial-lateral', posture: 'anatomical', perspective: 'front' }),
    item({ id: 'l1-proximal-distal', objectiveId: 'O-L1-proximal-distal', prompt: 'No membro superior, qual marcador está mais perto da ligação com o tronco?', accessiblePrompt: 'Escolha entre dois marcadores numerados no mesmo membro.', answerOptions: pair(option('proximal', 'Marcador 1', 'shoulder-marker', 'Marcador junto à ligação do braço com o tronco.'), option('distal', 'Marcador 2', 'wrist-marker', 'Marcador junto ao punho.')), correctAnswerId: 'proximal', evidenceKind: 'later_independent_retrieval', awardsXp: true, misconception: 'E-REL', feedback: { correct: 'Proximal se aproxima da ligação do membro.', incorrect: 'Use a ligação com o tronco como referência do membro.' }, remediationChallengeId: 'l1-assisted-proximal-distal', nextChallengeId: 'l1-superficial-deep', nextActionLabel: 'Continuar', reviewTargetId: 'review:l1:proximal-distal', posture: 'anatomical', perspective: 'front' }),
    item({ id: 'l1-superficial-deep', objectiveId: 'O-L1-superficial-deep', prompt: 'Qual marcador está na camada mais perto da superfície corporal?', accessiblePrompt: 'Escolha entre um marcador em contorno sólido externo e outro em camada tracejada interna.', answerOptions: pair(option('superficial', 'Marcador 1', 'outer-layer', 'Marcador no contorno sólido mais externo.'), option('deep', 'Marcador 2', 'inner-layer', 'Marcador na camada tracejada interna.')), correctAnswerId: 'superficial', evidenceKind: 'later_independent_retrieval', awardsXp: true, misconception: 'E-REL', feedback: { correct: 'Superficial está mais perto da superfície.', incorrect: 'Compare as duas camadas locais, não a altura delas no quadro.' }, remediationChallengeId: 'l1-assisted-superficial-deep', nextChallengeId: 'l1-transfer-posture', nextActionLabel: 'Continuar para mudança de postura', reviewTargetId: 'review:l1:superficial-deep', posture: 'anatomical', perspective: 'front' }),
    item({ id: 'l1-transfer-posture', objectiveId: 'O-L1-referencia-sob-mudanca-de-postura', prompt: 'Uma pessoa está em decúbito ventral. Qual superfície do tórax continua anterior?', accessiblePrompt: 'Escolha entre duas superfícies numeradas com padrões diferentes; a descrição não informa qual é anterior.', answerOptions: pair(option('anterior', 'Superfície 1', 'anterior-thorax', 'Painel 1 tem contorno contínuo e permanece voltado para baixo nesta postura.'), option('posterior', 'Superfície 2', 'posterior-thorax', 'Painel 2 tem traço pontilhado e permanece voltado para cima nesta postura.')), correctAnswerId: 'anterior', evidenceKind: 'later_independent_retrieval', awardsXp: true, misconception: 'E-GRV', feedback: { correct: 'Anterior continua sendo a frente do corpo; a referência anatômica não vira cima ou baixo quando a pessoa deita.', incorrect: 'Não use a gravidade como referência. Anterior e posterior permanecem definidos pelo corpo, mesmo em outra postura.' }, remediationChallengeId: 'l1-assisted-posture', reviewTargetId: 'review:l1:postura-e-referencia', posture: 'prone', perspective: 'front' }),
    item({ id: 'l1-assisted-posture', objectiveId: 'O-L1-referencia-sob-mudanca-de-postura', prompt: 'Prática guiada: compare as duas superfícies antes de responder em uma nova postura.', accessiblePrompt: 'Prática guiada com duas superfícies numeradas e padrões diferentes.', answerOptions: pair(option('anterior', 'Superfície 1', 'anterior-thorax', 'Painel 1 tem contorno contínuo.'), option('posterior', 'Superfície 2', 'posterior-thorax', 'Painel 2 tem traço pontilhado.')), correctAnswerId: 'anterior', evidenceKind: 'assisted_practice', awardsXp: false, misconception: 'E-GRV', feedback: { correct: 'A relação é mantida pelo corpo, não pela direção em que ele está apoiado.', incorrect: 'Releia o contorno frontal e posterior: a postura mudou, a referência não.' }, remediationChallengeId: 'l1-assisted-posture', nextChallengeId: 'l1-posture-recovery', nextActionLabel: 'Tentar nova postura sem apoio', additionalRecoveryChallengeId: 'l1-posture-recovery-2', reviewTargetId: 'review:l1:postura-e-referencia', posture: 'supine', perspective: 'front' }),
    item({ id: 'l1-posture-recovery', objectiveId: 'O-L1-referencia-sob-mudanca-de-postura', prompt: 'Em decúbito dorsal, qual superfície do tórax continua posterior?', accessiblePrompt: 'Escolha entre duas superfícies numeradas em uma postura nova; a descrição não informa a resposta.', answerOptions: pair(option('posterior', 'Superfície 1', 'posterior-thorax', 'Painel 1 tem traço pontilhado e permanece voltado para baixo nesta postura.'), option('anterior', 'Superfície 2', 'anterior-thorax', 'Painel 2 tem contorno contínuo e permanece voltado para cima nesta postura.')), correctAnswerId: 'posterior', evidenceKind: 'later_independent_retrieval', awardsXp: true, misconception: 'E-GRV', feedback: { correct: 'Posterior continua sendo as costas do corpo, mesmo quando essa superfície está voltada para baixo.', incorrect: 'Não transforme a face apoiada em posterior por causa da gravidade.' }, remediationChallengeId: 'l1-assisted-posture', reviewTargetId: 'review:l1:postura-e-referencia', posture: 'supine', perspective: 'back' }),
    item({ id: 'l1-assisted-superior-inferior', objectiveId: 'O-L1-superior-inferior', prompt: 'Prática guiada: acompanhe a referência cabeça–pés antes de comparar os marcadores.', accessiblePrompt: 'Prática guiada com dois marcadores numerados junto à cabeça e aos pés.', answerOptions: pair(option('superior', 'Marcador 1', 'head-marker', 'Marcador junto à extremidade da cabeça.'), option('inferior', 'Marcador 2', 'foot-marker', 'Marcador junto à extremidade dos pés.')), correctAnswerId: 'superior', evidenceKind: 'assisted_practice', awardsXp: false, misconception: 'E-REL', feedback: { correct: 'A referência cabeça–pés permanece disponível para comparar os dois marcadores.', incorrect: 'Comece pela cabeça e siga para os pés; não compare a altura no quadro.' }, remediationChallengeId: 'l1-assisted-superior-inferior', nextChallengeId: 'l1-superior-inferior-recovery', nextActionLabel: 'Tentar novo cenário sem apoio', additionalRecoveryChallengeId: 'l1-superior-inferior-recovery-2', reviewTargetId: 'review:l1:superior-inferior', posture: 'supine', perspective: 'front' }),
    item({ id: 'l1-superior-inferior-recovery', objectiveId: 'O-L1-superior-inferior', prompt: 'Em decúbito dorsal, qual marcador continua mais próximo da cabeça?', accessiblePrompt: 'Escolha entre dois marcadores numerados em uma postura nova.', answerOptions: pair(option('superior', 'Marcador 1', 'head-marker', 'Marcador junto à extremidade da cabeça.'), option('inferior', 'Marcador 2', 'foot-marker', 'Marcador junto à extremidade dos pés.')), correctAnswerId: 'superior', evidenceKind: 'later_independent_retrieval', awardsXp: true, misconception: 'E-REL', feedback: { correct: 'A postura mudou, mas superior continua relacionado à cabeça.', incorrect: 'Retome a referência cabeça–pés do corpo, não a orientação da tela.' }, remediationChallengeId: 'l1-assisted-superior-inferior', nextChallengeId: 'l1-medial-lateral', nextActionLabel: 'Continuar', reviewTargetId: 'review:l1:superior-inferior', posture: 'supine', perspective: 'front' }),
    item({ id: 'l1-assisted-medial-lateral', objectiveId: 'O-L1-medial-lateral', prompt: 'Prática guiada: use a linha mediana tracejada para comparar os dois marcadores.', accessiblePrompt: 'Prática guiada com um marcador junto à linha mediana e outro no contorno externo.', answerOptions: pair(option('medial', 'Marcador 1', 'midline-marker', 'Marcador junto à linha tracejada central.'), option('lateral', 'Marcador 2', 'outer-arm-marker', 'Marcador junto ao contorno externo do braço.')), correctAnswerId: 'medial', evidenceKind: 'assisted_practice', awardsXp: false, misconception: 'E-REL', feedback: { correct: 'A linha mediana é a referência para reconhecer medial.', incorrect: 'Compare a distância até a linha mediana, não até a borda do desenho.' }, remediationChallengeId: 'l1-assisted-medial-lateral', nextChallengeId: 'l1-medial-lateral-recovery', nextActionLabel: 'Tentar novo cenário sem apoio', additionalRecoveryChallengeId: 'l1-medial-lateral-recovery-2', reviewTargetId: 'review:l1:medial-lateral', posture: 'anatomical', perspective: 'back' }),
    item({ id: 'l1-medial-lateral-recovery', objectiveId: 'O-L1-medial-lateral', prompt: 'Agora em vista posterior, qual marcador está mais próximo da linha mediana?', accessiblePrompt: 'Escolha entre dois marcadores numerados em uma vista nova.', answerOptions: pair(option('medial', 'Marcador 1', 'midline-marker', 'Marcador junto à linha tracejada central.'), option('lateral', 'Marcador 2', 'outer-arm-marker', 'Marcador junto ao contorno externo do braço.')), correctAnswerId: 'medial', evidenceKind: 'later_independent_retrieval', awardsXp: true, misconception: 'E-REL', feedback: { correct: 'Vista posterior não altera a relação com a linha mediana.', incorrect: 'Localize primeiro a linha mediana e então compare os marcadores.' }, remediationChallengeId: 'l1-assisted-medial-lateral', nextChallengeId: 'l1-proximal-distal', nextActionLabel: 'Continuar', reviewTargetId: 'review:l1:medial-lateral', posture: 'anatomical', perspective: 'back' }),
    item({ id: 'l1-assisted-proximal-distal', objectiveId: 'O-L1-proximal-distal', prompt: 'Prática guiada: encontre a ligação do membro com o tronco antes de comparar os marcadores.', accessiblePrompt: 'Prática guiada com dois marcadores numerados no mesmo membro.', answerOptions: pair(option('proximal', 'Marcador 1', 'shoulder-marker', 'Marcador junto à ligação do braço com o tronco.'), option('distal', 'Marcador 2', 'wrist-marker', 'Marcador junto ao punho.')), correctAnswerId: 'proximal', evidenceKind: 'assisted_practice', awardsXp: false, misconception: 'E-REL', feedback: { correct: 'A ligação com o tronco organiza proximal e distal no membro.', incorrect: 'Use o ponto de ligação com o tronco, não a altura na tela.' }, remediationChallengeId: 'l1-assisted-proximal-distal', nextChallengeId: 'l1-proximal-distal-recovery', nextActionLabel: 'Tentar novo cenário sem apoio', additionalRecoveryChallengeId: 'l1-proximal-distal-recovery-2', reviewTargetId: 'review:l1:proximal-distal', posture: 'supine', perspective: 'front' }),
    item({ id: 'l1-proximal-distal-recovery', objectiveId: 'O-L1-proximal-distal', prompt: 'Com a pessoa deitada, qual marcador do braço continua mais próximo do tronco?', accessiblePrompt: 'Escolha entre dois marcadores numerados no mesmo membro, em uma postura nova.', answerOptions: pair(option('proximal', 'Marcador 1', 'shoulder-marker', 'Marcador junto à ligação do braço com o tronco.'), option('distal', 'Marcador 2', 'wrist-marker', 'Marcador junto ao punho.')), correctAnswerId: 'proximal', evidenceKind: 'later_independent_retrieval', awardsXp: true, misconception: 'E-REL', feedback: { correct: 'Proximal continua junto à ligação com o tronco, mesmo quando a pessoa deita.', incorrect: 'Volte à ligação do braço com o tronco antes de comparar os pontos.' }, remediationChallengeId: 'l1-assisted-proximal-distal', nextChallengeId: 'l1-superficial-deep', nextActionLabel: 'Continuar', reviewTargetId: 'review:l1:proximal-distal', posture: 'supine', perspective: 'front' }),
    item({ id: 'l1-assisted-superficial-deep', objectiveId: 'O-L1-superficial-deep', prompt: 'Prática guiada: compare o contorno externo sólido com a camada tracejada interna.', accessiblePrompt: 'Prática guiada com duas camadas numeradas e distinguidas por contorno e texto.', answerOptions: pair(option('superficial', 'Marcador 1', 'outer-layer', 'Marcador no contorno sólido mais externo.'), option('deep', 'Marcador 2', 'inner-layer', 'Marcador na camada tracejada interna.')), correctAnswerId: 'superficial', evidenceKind: 'assisted_practice', awardsXp: false, misconception: 'E-REL', feedback: { correct: 'O contorno externo identifica a camada superficial, sem depender de cor.', incorrect: 'Compare a camada externa contínua com a interna tracejada.' }, remediationChallengeId: 'l1-assisted-superficial-deep', nextChallengeId: 'l1-superficial-deep-recovery', nextActionLabel: 'Tentar novo cenário sem apoio', additionalRecoveryChallengeId: 'l1-superficial-deep-recovery-2', reviewTargetId: 'review:l1:superficial-deep', posture: 'anatomical', perspective: 'back' }),
    item({ id: 'l1-superficial-deep-recovery', objectiveId: 'O-L1-superficial-deep', prompt: 'Na vista posterior, qual marcador continua na camada mais próxima da superfície corporal?', accessiblePrompt: 'Escolha entre duas camadas numeradas em uma vista nova.', answerOptions: pair(option('superficial', 'Marcador 1', 'outer-layer', 'Marcador no contorno sólido mais externo.'), option('deep', 'Marcador 2', 'inner-layer', 'Marcador na camada tracejada interna.')), correctAnswerId: 'superficial', evidenceKind: 'later_independent_retrieval', awardsXp: true, misconception: 'E-REL', feedback: { correct: 'A mudança de vista não troca a camada externa pela interna.', incorrect: 'Compare os dois padrões de camada localmente, sem usar posição na tela.' }, remediationChallengeId: 'l1-assisted-superficial-deep', nextChallengeId: 'l1-transfer-posture', nextActionLabel: 'Continuar para mudança de postura', reviewTargetId: 'review:l1:superficial-deep', posture: 'anatomical', perspective: 'back' }),
    item({ id: 'l1-laterality-recovery-2', objectiveId: 'O-L1-lateralidade-corpo-observador', prompt: 'Com a pessoa em decúbito dorsal, qual mão continua pertencendo ao lado esquerdo dela?', accessiblePrompt: 'Escolha entre duas mãos numeradas em uma postura nova; a descrição não informa a resposta.', answerOptions: pair(leftFront, rightFront), correctAnswerId: 'patient-left', evidenceKind: 'later_independent_retrieval', awardsXp: true, misconception: 'E-LAT-OBS', feedback: { correct: 'A postura não troca a lateralidade do corpo.', incorrect: 'Direita e esquerda continuam pertencendo à pessoa descrita, não à tela.' }, remediationChallengeId: 'l1-remediate-laterality', nextChallengeId: 'l1-superior-inferior', nextActionLabel: 'Continuar para relações do corpo', reviewTargetId: 'review:l1:lateralidade-em-nova-postura', posture: 'supine', perspective: 'front' }),
    item({ id: 'l1-posture-recovery-2', objectiveId: 'O-L1-referencia-sob-mudanca-de-postura', prompt: 'Na posição anatômica vista por trás, qual superfície do tórax continua anterior?', accessiblePrompt: 'Escolha entre duas superfícies numeradas em uma vista nova; a descrição não informa a resposta.', answerOptions: pair(option('anterior', 'Superfície 1', 'anterior-thorax', 'Painel 1 tem contorno contínuo.'), option('posterior', 'Superfície 2', 'posterior-thorax', 'Painel 2 tem traço pontilhado.')), correctAnswerId: 'anterior', evidenceKind: 'later_independent_retrieval', awardsXp: true, misconception: 'E-GRV', feedback: { correct: 'Anterior continua sendo a frente do corpo, inclusive na vista posterior.', incorrect: 'Vista e postura não trocam frente e costas do corpo.' }, remediationChallengeId: 'l1-assisted-posture', reviewTargetId: 'review:l1:postura-e-referencia', posture: 'anatomical', perspective: 'back' }),
    item({ id: 'l1-superior-inferior-recovery-2', objectiveId: 'O-L1-superior-inferior', prompt: 'Em decúbito ventral, qual marcador está mais próximo dos pés?', accessiblePrompt: 'Escolha entre dois marcadores numerados em uma postura nova.', answerOptions: pair(option('inferior', 'Marcador 1', 'foot-marker', 'Marcador junto à extremidade dos pés.'), option('superior', 'Marcador 2', 'head-marker', 'Marcador junto à extremidade da cabeça.')), correctAnswerId: 'inferior', evidenceKind: 'later_independent_retrieval', awardsXp: true, misconception: 'E-REL', feedback: { correct: 'Inferior continua relacionado aos pés, mesmo em decúbito.', incorrect: 'Retome a referência pés–cabeça do corpo.' }, remediationChallengeId: 'l1-assisted-superior-inferior', nextChallengeId: 'l1-medial-lateral', nextActionLabel: 'Continuar', reviewTargetId: 'review:l1:superior-inferior', posture: 'prone', perspective: 'back' }),
    item({ id: 'l1-medial-lateral-recovery-2', objectiveId: 'O-L1-medial-lateral', prompt: 'Em decúbito dorsal, qual marcador permanece mais próximo da linha mediana?', accessiblePrompt: 'Escolha entre dois marcadores numerados em uma postura nova.', answerOptions: pair(option('medial', 'Marcador 1', 'midline-marker', 'Marcador junto à linha tracejada central.'), option('lateral', 'Marcador 2', 'outer-arm-marker', 'Marcador junto ao contorno externo do braço.')), correctAnswerId: 'medial', evidenceKind: 'later_independent_retrieval', awardsXp: true, misconception: 'E-REL', feedback: { correct: 'A linha mediana mantém a relação medial na nova postura.', incorrect: 'Compare os marcadores com a linha mediana do corpo.' }, remediationChallengeId: 'l1-assisted-medial-lateral', nextChallengeId: 'l1-proximal-distal', nextActionLabel: 'Continuar', reviewTargetId: 'review:l1:medial-lateral', posture: 'supine', perspective: 'front' }),
    item({ id: 'l1-proximal-distal-recovery-2', objectiveId: 'O-L1-proximal-distal', prompt: 'Na vista posterior, qual marcador do braço continua mais perto da ligação com o tronco?', accessiblePrompt: 'Escolha entre dois marcadores numerados em uma vista nova.', answerOptions: pair(option('proximal', 'Marcador 1', 'shoulder-marker', 'Marcador junto à ligação do braço com o tronco.'), option('distal', 'Marcador 2', 'wrist-marker', 'Marcador junto ao punho.')), correctAnswerId: 'proximal', evidenceKind: 'later_independent_retrieval', awardsXp: true, misconception: 'E-REL', feedback: { correct: 'A ligação com o tronco é a mesma em qualquer vista.', incorrect: 'Localize a ligação do membro com o tronco.' }, remediationChallengeId: 'l1-assisted-proximal-distal', nextChallengeId: 'l1-superficial-deep', nextActionLabel: 'Continuar', reviewTargetId: 'review:l1:proximal-distal', posture: 'prone', perspective: 'back' }),
    item({ id: 'l1-superficial-deep-recovery-2', objectiveId: 'O-L1-superficial-deep', prompt: 'Em decúbito dorsal, qual marcador permanece na camada externa?', accessiblePrompt: 'Escolha entre duas camadas numeradas em uma postura nova.', answerOptions: pair(option('superficial', 'Marcador 1', 'outer-layer', 'Marcador no contorno sólido mais externo.'), option('deep', 'Marcador 2', 'inner-layer', 'Marcador na camada tracejada interna.')), correctAnswerId: 'superficial', evidenceKind: 'later_independent_retrieval', awardsXp: true, misconception: 'E-REL', feedback: { correct: 'A camada superficial continua mais perto da superfície corporal.', incorrect: 'Compare o contorno externo contínuo com a camada interna tracejada.' }, remediationChallengeId: 'l1-assisted-superficial-deep', nextChallengeId: 'l1-transfer-posture', nextActionLabel: 'Continuar para mudança de postura', reviewTargetId: 'review:l1:superficial-deep', posture: 'supine', perspective: 'back' }),
  ],
  sequence: ['l1-diagnostic-laterality', 'l1-laterality-transfer', 'l1-superior-inferior', 'l1-medial-lateral', 'l1-proximal-distal', 'l1-superficial-deep', 'l1-transfer-posture'],
  synthesis: ['A posição anatômica oferece uma referência compartilhada para descrever relações.', 'Direita e esquerda pertencem ao corpo descrito, não a quem olha.', 'Mudar a postura não muda anterior, posterior, superior ou inferior.'],
  reviewPlan: ['R1: recuperação independente após dois outros nós, com postura diferente.', 'R2: recuperação independente após cinco a oito nós, em contexto de imagem novo.'],
};
